create TABLE IF NOT EXISTS users (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uniq_email UNIQUE (email)
);

create TABLE IF NOT EXISTS categories (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(50) NOT NULL,
    CONSTRAINT pk_cats PRIMARY KEY (id),
    CONSTRAINT uniq_cat_name UNIQUE (name)
);

create TABLE IF NOT EXISTS compilations (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned       BOOLEAN,
    title VARCHAR(50) NOT NULL,
    CONSTRAINT pk_compls PRIMARY KEY (id)
);

create TABLE IF NOT EXISTS events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation   VARCHAR(2000) NOT NULL,
    category_id  BIGINT NOT NULL,
    created_on   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description  VARCHAR(7000) NOT NULL,
    event_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id BIGINT NOT NULL,
    paid         boolean,
    participant_limit BIGINT,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    request_moderation boolean,
    state        VARCHAR(10) NOT NULL,
    title        VARCHAR(120) NOT NULL,
    location_lat FLOAT NOT NULL,
    location_lon FLOAT NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT fk_cat_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_init_user FOREIGN KEY (initiator_id) REFERENCES users (id)
);

create TABLE IF NOT EXISTS events_compilations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id       BIGINT NOT NULL,
    compilation_id BIGINT NOT NULL,
    CONSTRAINT key_uniq PRIMARY KEY (event_id, compilation_id),
    CONSTRAINT fk_id_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT fk_id_compl FOREIGN KEY (compilation_id) REFERENCES compilations (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    requester_id BIGINT NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id     BIGINT NOT NULL,
    status       VARCHAR(10),
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT fk_requester_user FOREIGN KEY (requester_id) REFERENCES users (id),
    CONSTRAINT fk_event_event FOREIGN KEY (event_id) REFERENCES events (id)
);